site_name: OpenIndiana Reimagined
site_url: https://n00b-5634.github.io/OpenIndiana-SiteReimagined/
site_dir: site_docs

theme:
  name: null
  custom_dir: overrides  # Best to use a folder for your main.html template

extra_css:
  - css/style.css
