site_name: OpenIndiana Reimagined
site_url: https://n00b-5634.github.io/OpenIndiana-SiteReimagined/
site_dir: site_docs

theme:
  name: mkdocs
  custom_dir: overrides
  search_index_only:

extra_css:
  - css/style.css
